[package]
name = "pso2server"
version = "0.1.0"
edition = "2021"
default-run = "pso2server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "map-transform"
path = "src/map_transformer.rs"

[dependencies]
byteorder = "1.4.3"
rand = "0.8.5"
rsa = "0.9.2"
pso2packetlib = { git = "https://github.com/AntonnMal/pso2-protocol-lib", rev = "a5adc13", features = ["serde", "connection", "vita_enc", "base_enc"] }
sqlite = "0.31.0"
thiserror = "1.0.40"
serde_json = "1.0.99"
argon2 = "0.5.0"
half = "2.3.1"
rmp-serde = "1.1.2"
serde = "1.0.174"
