[workspace]

members = ["ship_server", "data_compiler", "data_structs", "master_ship"]
resolver = "2"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "map-transform"
path = "src/map_transformer.rs"

[dependencies]
byteorder = "1.4.3"
rand = "0.8.5"
rsa = "0.9.2"
pso2packetlib = { git = "https://github.com/PhantasyServer/pso2-protocol-lib", rev = "2070914", default-features = false, features = ["serde", "connection", "vita_enc", "base_enc", "ppac", "item_attrs"] }
sqlite = "0.31.0"
thiserror = "1.0.40"
serde_json = "1.0.99"
argon2 = "0.5.0"
half = "2.3.1"
rmp-serde = "1.1.2"
serde = "1.0.174"
memory-stats = "1.1.0"
mlua = { version = "0.9.1", features = ["serialize", "luajit", "vendored"] }
parking_lot = "0.12.1"
crc32fast = "1.3.2"
indicatif = "0.17.7"
console = "0.15.7"
