[package]
name = "pso2server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
rand = "0.8.5"
rsa = "0.9.2"
tokio = {version = "1.25.0", features = ["macros", "time", "rt-multi-thread"] }
pso2packetlib = { git = "https://github.com/AntonnMal/pso2-protocol-lib", features = ["serde"] }
sqlite = "0.31.0"
thiserror = "1.0.40"
serde_json = "1.0.99"
argon2 = "0.5.0"
