[package]
name = "pso2server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
chrono = "0.4.24"
rand = "0.8.5"
rsa = "0.9.2"
tokio = {version = "1.25.0", features = ["net", "macros", "time", "rt-multi-thread"] }
pso2packetlib = { git = "https://github.com/AntonnMal/pso2-protocol-lib" }