[workspace]

members = ["ship_server", "data_compiler", "data_structs", "master_ship", "ppac_reader"]
resolver = "2"

[workspace.dependencies]
# pso2packetlib = { path = "../pso2packetlib", default-features = false }
pso2packetlib = { git = "https://github.com/PhantasyServer/pso2-protocol-lib", rev = "fc85689", default-features = false }

[profile.release]
lto = true
