[package]
name = "pso2ship_server"
version = "0.1.0"
edition = "2021"
default-run = "pso2ship_server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
rand = "0.8.5"
rsa = "0.9.2"
pso2packetlib = { workspace = true, default-features = false, features = ["serde", "connection", "vita_enc", "base_enc", "ppac", "item_attrs"] }
sqlx = { version = "0.7.3", default-features = false, features = ["any", "runtime-tokio", "sqlite", "mysql", "migrate"] }
thiserror = "1.0.50"
serde_json = "1.0.111"
rmp-serde = "1.1.2" 
half = "2.3.1"
serde = "1.0.195"
memory-stats = "1.1.0"
mlua = { version = "0.9.4", features = ["serialize", "luajit", "vendored", "send", "async"] }
parking_lot = {version = "0.12.1", features = ["send_guard"]}
crc32fast = "1.3.2"
indicatif = "0.17.7"
console = "0.15.8"
data_structs = { path = "../data_structs", features = ["rmp", "ship"] }
tokio = { version = "1.35.1", features = ["full"] }
toml = "0.8.8"
