[package]
name = "pso2ship_server"
version = "0.1.0"
edition = "2021"
default-run = "pso2ship_server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
rand = "0.8.5"
rsa = "0.9.6"
pso2packetlib = { workspace = true, default-features = false, features = ["serde", "split_connection", "vita_enc", "base_enc", "ppac", "item_attrs", "tokio"] }
sqlx = { version = "0.7.4", default-features = false, features = ["runtime-tokio", "sqlite", "migrate", "any"] }
thiserror = "1.0.61"
serde_json = "1.0.117"
rmp-serde = "1.3.0" 
half = "2.4.1"
serde = "1.0.203"
memory-stats = "1.1.0"
mlua = { version = "0.9.8", features = ["serialize", "vendored", "send", "async"] }
parking_lot = {version = "0.12.3", features = ["send_guard"]}
crc32fast = "1.4.2"
indicatif = "0.17.8"
data_structs = { path = "../data_structs", features = ["rmp", "ship"] }
tokio = { version = "1.37.0", features = ["full"] }
toml = "0.8.13"
log = { version = "0.4.21", features = ["serde", "release_max_level_info", "std"] }
simplelog = "0.12.2"

# luajit doesn't compile on musl or on arm
[target.'cfg(any(target_env = "musl", target_arch = "arm"))'.dependencies.mlua]
version = "0.9.8"
features = ["lua51"]
[target.'cfg(not(any(target_env = "musl", target_arch = "arm")))'.dependencies.mlua]
version = "0.9.8"
features = ["luajit"]
