[package]
name = "master_ship"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.35.1", features = ["full"] }
pso2packetlib = { workspace = true, features = ["serde", "connection"] }
parking_lot = { version = "0.12.1", features = ["send_guard"] }
data_structs = { path = "../data_structs", features = ["rmp", "ship"] }
sqlx = { version = "0.7.3", features = ["any", "runtime-tokio", "sqlite", "mysql"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
thiserror = "1.0.50"
argon2 = "0.5.3"
rand_core = "0.6.4"
toml = "0.8.8"
rmp-serde = "1.1.2"
